version: "3.9"

services:

  db:
    image: postgres:15
    container_name: primetrade_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: primetrade
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: primetrade_backend
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/primetrade
      JWT_SECRET: supersecret
      PORT: 5000
    ports:
      - "5000:5000"
    command: sh -c "npx prisma migrate deploy && npm run dev"

  frontend:
    build: ./frontend
    container_name: primetrade_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  pgdata: